authors:
  ardihikaru:
    name: Muhammad Febrian Ardiansyah
    description: System Architect
    avatar: https://avatars.githubusercontent.com/u/9791562
    url: https://github.com/ardihikaru
  fardhil:
    name: Fardhil
    description: Tech Writer
    avatar: https://avatars.githubusercontent.com/u/149473672
    url: https://github.com/sismedikafardil
